# Generated by Django 3.0 on 2019-12-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='r_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Icyumweru'), (2, 'Igihembwe'), (3, 'Umwaka')], default=1),
        ),
    ]
