# Generated by Django 3.0 on 2019-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20191222_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='igihe_itangirwa',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Icyumweru'), (2, 'Igihembwe'), (3, 'Umwaka')], default=1),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='r_type',
            field=models.CharField(max_length=300),
        ),
    ]
