# Generated by Django 3.0 on 2019-12-22 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20191222_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='initial_date',
            field=models.DateField(default=datetime.timedelta(days=51)),
        ),
    ]
