# Generated by Django 3.0 on 2019-12-22 14:02

import datetime
from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20191222_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='deadline',
            field=models.DateField(default=report.models.geting_date),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='initial_date',
            field=models.DateField(default=datetime.date(2019, 11, 1)),
        ),
    ]
