# Generated by Django 3.0 on 2019-12-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20191222_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttype',
            name='initial_date',
        ),
    ]
