# Generated by Django 2.2.2 on 2019-11-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_auto_20191120_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='UnusedTerassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Umuhigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umuhigo', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Ubwanikiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubwanikiro', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=50)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Pumps_in_Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pumps', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insemination', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='InkaZizakurikiranwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inka_zizakurikiranwa', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Ha_irrigated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_irrigated', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Girinka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girinka', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='Banana_and_Rehabilitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
        ),
    ]
