# Generated by Django 2.2.2 on 2019-11-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191120_1601'),
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banana_and_rehabilitation',
            options={'verbose_name': 'Banana and Rehabilitation', 'verbose_name_plural': 'Banana and Rehabilitation'},
        ),
        migrations.AlterModelOptions(
            name='crops',
            options={'verbose_name': 'Crops', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='fertilizers',
            options={'verbose_name': 'Fertilizers', 'verbose_name_plural': 'Fertilizers'},
        ),
        migrations.AlterModelOptions(
            name='girinka',
            options={'verbose_name': 'Girinka', 'verbose_name_plural': 'Girinka'},
        ),
        migrations.AlterModelOptions(
            name='ha_irrigated',
            options={'verbose_name': 'Ha Irrigated', 'verbose_name_plural': 'Ha Irrigated'},
        ),
        migrations.AlterModelOptions(
            name='inkazizakurikiranwa',
            options={'verbose_name': 'Inka Zizakurikiranwa', 'verbose_name_plural': 'Inka Zizakurikiranwa'},
        ),
        migrations.AlterModelOptions(
            name='insemination',
            options={'verbose_name': 'Insemination', 'verbose_name_plural': 'Insemination'},
        ),
        migrations.AlterModelOptions(
            name='pumps_in_sector',
            options={'verbose_name': 'Pumps in Sector', 'verbose_name_plural': 'Pumps in Sectors'},
        ),
        migrations.AlterModelOptions(
            name='seeds',
            options={'verbose_name': 'Seeds', 'verbose_name_plural': 'Seeds'},
        ),
        migrations.AlterModelOptions(
            name='trainings',
            options={'verbose_name': 'Trainings', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterModelOptions(
            name='ubwanikiro',
            options={'verbose_name': 'Ubwanikiro', 'verbose_name_plural': 'Ubwanikiro'},
        ),
        migrations.AlterModelOptions(
            name='umuhigo',
            options={'verbose_name': 'Umuhigo', 'verbose_name_plural': 'Umuhigo'},
        ),
        migrations.AlterModelOptions(
            name='unusedterassis',
            options={'verbose_name': 'Unused Terrasis', 'verbose_name_plural': 'Unused Terrassis'},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name': 'Vaccination', 'verbose_name_plural': 'Vaccinations'},
        ),
        migrations.CreateModel(
            name='FertilizerImprovedSeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Fertilizer and  Improved Seeds',
                'verbose_name_plural': 'Fertilizer and Improved Seeds',
            },
        ),
    ]
