# Generated by Django 2.2.2 on 2019-12-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191120_1601'),
        ('agriculture', '0003_agriculturekpi_newbanana_and_rehabilitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbanana_and_rehabilitation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newbanana_and_rehabilitation',
            name='sector',
        ),
        migrations.AlterUniqueTogether(
            name='banana_and_rehabilitation',
            unique_together={('name', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='crops',
            unique_together={('crop_name', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='fertilizerimprovedseeds',
            unique_together={('target', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='fertilizers',
            unique_together={('name', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='ha_irrigated',
            unique_together={('ha_irrigated', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='pumps_in_sector',
            unique_together={('number_of_pumps', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='seeds',
            unique_together={('seed_name', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='trainings',
            unique_together={('training_name', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='ubwanikiro',
            unique_together={('ubwanikiro', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='umuhigo',
            unique_together={('umuhigo', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='unusedterassis',
            unique_together={('name', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='vaccination',
            unique_together={('vaccination_name', 'sector')},
        ),
        migrations.DeleteModel(
            name='AgricultureKPI',
        ),
        migrations.DeleteModel(
            name='NewBanana_and_Rehabilitation',
        ),
    ]
