# Generated by Django 2.2.5 on 2019-10-08 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboad.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboad.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TransportMean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tansport_mean', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboad.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Eg- 123,12A etc', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(help_text='Eg- example@gmail.com', max_length=254)),
                ('upload_file', models.FileField(null=True, upload_to='request_doc')),
                ('status', models.CharField(choices=[('Aproved', 'Aproved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Authorized', 'Authorized')], default='Pending', max_length=50)),
                ('requested_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboad.Category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboad.Department')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboad.StaffFunction')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboad.SchoolModel')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboad.TransportMean')),
            ],
        ),
        migrations.CreateModel(
            name='Requeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pendding'), (1, 'Approved'), (2, 'Rejected'), (3, 'Authorised')], default=0)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboad.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('note', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboad.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('destnation', models.CharField(max_length=100)),
                ('distance', models.CharField(help_text='Eg- 4km', max_length=40)),
                ('dipature_date', models.DateField(help_text='Eg- YY-MM-DD')),
                ('returnning_date', models.DateField(help_text='Eg- YY-MM-DD')),
                ('duration_of_mission', models.TimeField(help_text='Eg- HH:MM')),
                ('invitation_latter', models.FileField(upload_to='')),
                ('staff_issued_to', models.ManyToManyField(to='dashboad.Staff')),
            ],
        ),
    ]
