# Generated by Django 2.2.5 on 2019-10-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolmodel',
            name='category',
        ),
    ]
