# Generated by Django 2.2.5 on 2019-10-17 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboad', '0002_remove_schoolmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmodel',
            name='superviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Eg- 123,12A etc', max_length=20, null=True),
        ),
    ]
