# Generated by Django 2.2.5 on 2019-10-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0003_auto_20191017_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='category',
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboad.SchoolModel'),
        ),
    ]
