# Generated by Django 2.2.5 on 2019-10-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0005_auto_20191022_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='staff',
        ),
        migrations.AlterField(
            model_name='mission',
            name='duration_of_mission',
            field=models.CharField(help_text='Eg- 10 days and 10 nights', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='upload_file',
            field=models.FileField(blank=True, help_text='upload your invitstion latter', null=True, upload_to='request_doc'),
        ),
    ]
