# Generated by Django 2.2.5 on 2019-11-03 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboad', '0006_auto_20191029_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolmodel',
            name='superviser',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(help_text='Upload .pdf file', upload_to=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='school_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Requeste',
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboad.SchoolModel'),
        ),
        migrations.AddField(
            model_name='schoolsupervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
