# Generated by Django 2.2.5 on 2019-11-03 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0007_auto_20191103_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboad.Category'),
        ),
        migrations.AlterField(
            model_name='stafffunction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboad.Category'),
        ),
    ]
