# Generated by Django 2.2.5 on 2019-11-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0008_auto_20191103_2243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffFunction',
            new_name='Role',
        ),
    ]
