# Generated by Django 3.0.1 on 2019-12-23 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='deadline',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 23, 16, 41, 59, 632461)),
        ),
    ]
