# Generated by Django 3.0.1 on 2019-12-23 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20191223_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 16, 43, 22, 19387)),
        ),
    ]
