# Generated by Django 3.0.1 on 2019-12-23 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20191223_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='deadline',
            field=models.DateTimeField(default=datetime.date(2019, 12, 4)),
        ),
    ]
