# Generated by Django 2.2.5 on 2019-10-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboad', '0002_remove_schoolmodel_category'),
        ('urmas_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboad.SchoolModel'),
        ),
    ]
