# Generated by Django 2.2.5 on 2019-10-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmas_users', '0003_auto_20191016_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/static/images/profile.png', null=True, upload_to='img'),
        ),
    ]
