# Generated by Django 2.2.7 on 2019-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='climate',
            field=models.CharField(choices=[('hot', 'hot'), ('cold', 'cold')], default='Undefined', max_length=100),
        ),
    ]
