# Generated by Django 2.2.7 on 2019-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_kpi_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='achieved',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='pending',
            field=models.PositiveIntegerField(),
        ),
    ]
