# Generated by Django 2.2.3 on 2019-09-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('plot', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'NR - Not Rated'), (1, ' G - General Audience'), (2, 'PG - Parent Guidence Suggested'), (3, 'R - Restricted')], default=0)),
                ('runtime', models.IntegerField()),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
