# Generated by Django 3.0.1 on 2019-12-29 10:36

from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0024_auto_20191222_1822'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=300)),
                ('igihe_itangirwa', models.PositiveSmallIntegerField(choices=[(1, 'Icyumweru'), (2, 'Igihembwe'), (3, 'Umwaka')])),
                ('deadline', models.DateTimeField(default=report.models.get_deadline)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports')),
                ('submited_date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportType')),
            ],
        ),
    ]
